language: node_js

sudo: false

node_js:
  - 'node'

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi

install:
  - npm i
  - npm i ./packages/core/colors   packages/core
  - npm i ./packages/core/builders packages/insomnia
  - npm i ./packages/core/builders packages/vscode
  - npm i ./packages/core/builders packages/kitty
  - npm i ./packages/core/builders packages/alacritty
  - npm i ./packages/core/builders packages/ulauncher
  - npm run build

script:
  - npm test --silent

after_success:
  - npm run coverage
