colors:
  primary:
    background: '$primaryColor'
    foreground: '$white'
    dim_foreground: '$beige'
    bright_foreground: '$blush'
    dim_background: '$beige'
    bright_background: '$beige'

  cursor:
    text: '$grey'
    cursor: '$blush'

  normal:
    black: '$black'
    red: '$red'
    green: '$green'
    yellow: '$yellow'
    blue: '$blue'
    magenta: '$purple'
    cyan: '$cyan'
    white: '$white'
