name: release
on: [push]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    env:
      workdir: ./packages/themes

    steps:
      - name: Project -> Checkout
        uses: actions/checkout@v2

      - name: Project -> Set up Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Project -> Install Dependencies
        run: yarn install

      - name: Project -> Test
        run: yarn test

      - name: Project -> Build
        run: yarn build

      # VS Code
      - name: VS Code -> Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.workdir }}/vscode/flate-0.6.1.vsix
          asset_name: vscode.vsix
          tag: ${{ github.ref }}
          overwrite: true

      # Alacritty
      - name: Alacritty -> Pack
        run: (cd ${{ env.workdir }}/alacritty && zip -r alacritty.zip dist)

      - name: Alacritty -> Upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.workdir }}/alacritty/alacritty.zip
          asset_name: alacritty.zip
          tag: ${{ github.ref }}
          overwrite: true

      # Ulauncher
      - name: Ulauncher -> Pack
        run: (cd ${{ env.workdir }}/ulauncher && zip -r ulauncher.zip dist)

      - name: Ulauncher -> Upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.workdir }}/ulauncher/ulauncher.zip
          asset_name: ulauncher.zip
          tag: ${{ github.ref }}
          overwrite: true

      # Insomnia
      - name: Insomnia -> Pack
        run: (cd ${{ env.workdir }}/insomnia && zip -r insomnia.zip dist index.js package.json)

      - name: Insomnia -> Upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.workdir }}/insomnia/insomnia.zip
          asset_name: insomnia.zip
          tag: ${{ github.ref }}
          overwrite: true

      # Kitty
      - name: Kitty -> Pack
        run: (cd ${{ env.workdir }}/kitty && zip -r kitty.zip dist)

      - name: Kitty -> Upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.workdir }}/kitty/kitty.zip
          asset_name: kitty.zip
          tag: ${{ github.ref }}
          overwrite: true
